name: Repo_sync

on:
  repository_dispatch:
  workflow_dispatch:
  #schedule:
   # - cron: 30 16 * * *
  

env:
  TZ: Asia/Shanghai

jobs:
  New-Update-Files:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        pwd
        #临时备份本仓库readme
        mv README.md back.md
        mv .github/workflows/Kernel-compilation.yml .Kernel-compilation.yml
        mv .github/workflows/Repo_sync.yml ./Repo_sync.yml
        mv .github/workflows/delete-older-releases-artifacts.yml .delete-older-releases-artifacts.yml
        rm -rf .github/workflows
        mkdir -p .github/workflows
        svn export https://github.com/ophub/amlogic-s9xxx-armbian/trunk/ ./ --force        
        sed -i 's/custom_name="-ophub"/custom_name=""/g' ./recompile
        sed -i 's/default: "-ophub"/default: ""/g' ./action.yml
        sed -i 's/-ophub/custom_name=""/g' ./*
        #备份源仓库readme
        mv README.md READMEBACK.md
        #恢复本仓库readme
        mv back.md README.md
        mv ./Kernel-compilation.yml ./.github/workflows/Kernel-compilation.yml
        mv ./Repo_sync.yml ./.github/workflows/Repo_sync.yml
        mv ./delete-older-releases-artifacts.yml  ./.github/workflows/delete-older-releases-artifacts.yml
         
    - name: Commit
      run: |
        git config --global user.email 349589369@qq.com
        git config --global user.name Jejz168
        git add .
        git commit -m"action:`date`"
        git pull --rebase
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}        
   
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0
        keep_minimum_runs: 3
