name: Repo_sync

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 30 18 * * *
  

env:
  TZ: Asia/Shanghai

jobs:
  New-Update-Files:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        pwd
        #临时备份本仓库readme
        mv README.md back.md
        function git_sparse_clone(){
          repo=$(echo $1 | rev | cut -d'/' -f 1 | rev)
          pkg=$(echo $2 | rev | cut -d'/' -f 1 | rev)
          git clone --depth=1 --single-branch $1
          mv $2 ./
          rm -rf $repo
        }
        git_sparse_clone https://github.com/ophub/amlogic-s9xxx-armbian   
        sed -i 's/custom_name="-ophub"/custom_name=""/g' ./recompile
        sed -i 's/default: "-ophub"/default: ""/g' ./action.yml
        #备份源仓库readme
        mv README.md READMEBACK.md
        #恢复本仓库readme
        mv back.md README.md
        
    - name: Commit
      run: |
        git config --global user.email 349589369@qq.com
        git config --global user.name Jejz168
        git add .
        git commit -m"action:`date`"
        git pull --rebase
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}        
   
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0
        keep_minimum_runs: 3
